CLASE **1**

Phyton es un lenguaje versatil pero tiene  sus limitaciones

Numby es mas rapido y facil de organizar

Instalar Numpy

In [2]:
!pip install Numpy

In [1]:
import time
lista = list(range(10000000))
inicio = time.time()
[valor *2 for valor in lista ]
print("Tiempo de ejecucion con listas:", time.time()-inicio)

Tiempo de ejecucion con listas: 0.8934109210968018


ARREGLOS

In [3]:
import numpy as np
arreglo = np.array([2,2,2,2], dtype = float)
print(arreglo)

[2. 2. 2. 2.]


DIMENSIONES de los arreglos

In [ ]:
print("el numero de dimensiones del arreglo es : ", arreglo.ndim)

ARREGLO.size = numero de elementos
arreglo.shape = forma del arreglo
arreglo.dtype = tipo de datos(float,int, input) etc

EJEMPLO

In [7]:
arreglo3d = np.array([
    [[1,2,3],[5,6,7]],
    [[7,8,9],[10,11,12]]
])


In [8]:
print("el numero de dimensiones del arreglo es : ", arreglo3d.ndim)
print("la forma del arreglo es:", arreglo3d.shape)
print("el numero total de elementos del arreglo es:", arreglo3d.size)
print("los tipos de datos del arreglo son:", arreglo3d.dtype)

el numero de dimensiones del arreglo es :  3
la forma del arreglo es: (2, 2, 3)
el numero total de elementos del arreglo es: 12
los tipos de datos del arreglo son: int64


CLASE **2**

Ejemplo

In [10]:
import numpy as np
matriz1 = np.array([[1,2,3],
                    [4,0,-5],
                    [-6,-7,-8]])
print(matriz1)

[[ 1  2  3]
 [ 4  0 -5]
 [-6 -7 -8]]


Operaciones numericas con estas matrices

Sumas

In [12]:
go =(matriz1 + 10)
print(go)

[[11 12 13]
 [14 10  5]
 [ 4  3  2]]


se puede hacer las diferentes operciones como sumas, restas , divisiones , mult, etc

In [19]:
3 / matriz1

/tmp/ipykernel_6224/3743726649.py:1: RuntimeWarning: divide by zero encountered in divide
  3 / matriz1


array([[ 3.        ,  1.5       ,  1.        ],
       [ 0.75      ,         inf, -0.6       ],
       [-0.5       , -0.42857143, -0.375     ]])

In [21]:
matriz1[2,:]*3

array([-18, -21, -24])

In [20]:
matriz_a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

MODIFICACIONES Y DEMAS

In [13]:
arreglo = np.arange(9)
print(arreglo)

[0 1 2 3 4 5 6 7 8]


In [17]:
a = np. arange(12)
matriz_a = a.reshape(3,4)
print(matriz_a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


OPERADORES LOGICOS

In [18]:
print(matriz1 < 1)

[[False False False]
 [False  True  True]
 [ True  True  True]]
